### ISSUE TITLE
Would it be possible to tweak values in the generated JSON?

### ISSUE THREAD

**Issue by bieryAtFnal** [DUNE-DAQ/integrationtest#11]
It would be helpful to be able to modify the values of various configuration parameters even when they aren't control-lable via arguments to the confgen script.

For example, it would be nice to be able to modify the `max_file_size_bytes` parameter even though it is not one of the ones that `minidaqapp.nanorc.mdapp_multiru_gen` currently supports.

One naive way to support this might be to allow the test-driver files to run "sed" commands on the generated JSON.  But, it is not clear when/how this option might be given to writers of the test-driver files.  And, a security-conscious observer might say that this would allow code injection, which could be bad.

Maybe this Issue will be rejected in favor of adding command-line option(s) to minidaqapp.nanorc.mdapp_multiru_gen, but I wanted to ask nonetheless.

**Comment by eflumerf** [comment]
I believe this issue is completely obsoleted by the change to using DAQConf config files, and giving the integration tests dictionary-based access to that config.
